//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoPA.BaseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CINE_DBEntities : DbContext
    {
        public CINE_DBEntities()
            : base("name=CINE_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCompra> tCompra { get; set; }
        public virtual DbSet<tErrorLog> tErrorLog { get; set; }
        public virtual DbSet<tFuncion> tFuncion { get; set; }
        public virtual DbSet<tGenero> tGenero { get; set; }
        public virtual DbSet<tPelicula> tPelicula { get; set; }
        public virtual DbSet<tReserva> tReserva { get; set; }
        public virtual DbSet<tRoles> tRoles { get; set; }
        public virtual DbSet<tSala> tSala { get; set; }
        public virtual DbSet<tUsuario> tUsuario { get; set; }
    
        public virtual int sp_Reserva(Nullable<int> idPelicula, Nullable<System.DateTime> fecha, Nullable<int> sala, Nullable<int> cantidadBoletos)
        {
            var idPeliculaParameter = idPelicula.HasValue ?
                new ObjectParameter("IdPelicula", idPelicula) :
                new ObjectParameter("IdPelicula", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var salaParameter = sala.HasValue ?
                new ObjectParameter("Sala", sala) :
                new ObjectParameter("Sala", typeof(int));
    
            var cantidadBoletosParameter = cantidadBoletos.HasValue ?
                new ObjectParameter("CantidadBoletos", cantidadBoletos) :
                new ObjectParameter("CantidadBoletos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Reserva", idPeliculaParameter, fechaParameter, salaParameter, cantidadBoletosParameter);
        }
    }
}
