//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoPA.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCompra
    {
        public int id_compra { get; set; }
        public int id_usuario { get; set; }
        public int id_reserva { get; set; }
        public System.DateTime fecha_compra { get; set; }
        public string metodo_pago { get; set; }
        public decimal total { get; set; }
    
        public virtual tUsuario tUsuario { get; set; }
    }
}
