//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoPA.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tErrorLog
    {
        public int ErrorID { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> ErrorDateTime { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
