//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoPA.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFuncion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tFuncion()
        {
            this.tReserva = new HashSet<tReserva>();
        }
    
        public int id_funcion { get; set; }
        public int id_pelicula { get; set; }
        public int id_sala { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public decimal precio { get; set; }
    
        public virtual tPelicula tPelicula { get; set; }
        public virtual tSala tSala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReserva> tReserva { get; set; }
    }
}
