//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoPA.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tReserva()
        {
            this.tCompra = new HashSet<tCompra>();
        }
    
        public int id_reserva { get; set; }
        public int id_usuario { get; set; }
        public int id_funcion { get; set; }
        public int cantidad_entradas { get; set; }
        public System.DateTime fecha_reserva { get; set; }
        public decimal total_pagado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCompra> tCompra { get; set; }
        public virtual tFuncion tFuncion { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
